[Metadata]
Name = 'Clean Up Test TMP Artifacts'
Description = """
Clean up all artifacts for a job.
"""

[Variables]
Job = 'test'
MonteurPath = '.monteurFS'


[FMTVariables]
Target = '{{- .RootDir -}}/{{- .MonteurPath -}}/tmp/{{- .Job -}}'



[[CMD]]
Name = "Remove Target Directory"
Type = 'delete-recursive-quiet'
Condition = [ 'all-all' ]
Source = '{{- .Target -}}'

[[CMD]]
Name = "Create Target Directory"
Type = 'create-path'
Condition = [ 'all-all' ]
Source = '{{- .Target -}}'
