# Copyright 2024 HestiaKERNEL Authors
#
#
# Licensed under (Holloway) Chew, Kean Ho’s Liberal License (the "License").
# You must comply with the license to use the content. Get the License at:
#
#                 https://doi.org/10.5281/zenodo.13770769
#
# You MUST ensure any interaction with the content STRICTLY COMPLIES with
# the permissions and limitations set forth in the license.

# WARNING - Autogenerated script from 'HestiaKERNEL/src/unicode/data-parser.sh'.
#           DO NOT EDIT MANUALLY!




function hestiakernel-rune-to-lower {
        param (
                [uint32]$___char_decimal,
                [uint32]$___next_decimal,
                [uint32]$___third_decimal,
                [string]$___locale
        )


        # validate input
        if ($___char_decimal -eq "") {
                # ERROR - bad input
                return ""
        }


        # language sensitive special cases
        switch -Wildcard ($___locale) {
        { $_ -in "az*", "tr*" } {
                # Turkish & Azerbaijani
                switch ($___char_decimal) {
                0x0130 {
                        return "[1]105"
                } 0x0049 {
                        switch ($___next_decimal) {
                        0x0307 {
                                return "[2]105"
                        } default {
                                return "[1]305"
                        }}
                }}
        } "lt*" {
                # Lithuanian
                switch ($___char_decimal) {
                0x0049 {
                        return "[1]105, 775"
                } 0x004A {
                        return "[1]106, 775"
                } 0x012E {
                        return "[1]303, 775"
                } 0x00CC {
                        return "[1]105, 775, 768"
                } 0x00CD {
                        return "[1]105, 775, 769"
                } 0x0128 {
                        return "[1]105, 775, 771"
                }}
        }}


        # language insensitive special cases
        switch ($___char_decimal) {
        "powershell-language-adjusting-first-case" {
                # just to make the first case consistent with others (as in
                # programming languages) without breaking the parser just for
                # PowerShell specific requirement.
        } 0x0041 {
                switch ($___next_decimal) {
                0x02BE {
                        return "[2]7834"
                }}
        } 0x0046 {
                switch ($___next_decimal) {
                0x0046 {
                        switch ($___third_decimal) {
                        0x0049 {
                                return "[3]64259"
                        } 0x004C {
                                return "[3]64260"
                        } default {
                                return "[2]64256"
                        }}
                } 0x0049 {
                        return "[2]64257"
                } 0x004C {
                        return "[2]64258"
                } 0x0066 {
                        switch ($___third_decimal) {
                        0x0069 {
                                return "[3]64259"
                        } 0x006C {
                                return "[3]64260"
                        } default {
                                return "[2]64256"
                        }}
                } 0x0069 {
                        return "[2]64257"
                } 0x006C {
                        return "[2]64258"
                }}
        } 0x0048 {
                switch ($___next_decimal) {
                0x0331 {
                        return "[2]7830"
                }}
        } 0x004A {
                switch ($___next_decimal) {
                0x030C {
                        return "[2]496"
                }}
        } 0x0053 {
                switch ($___next_decimal) {
                0x0053 {
                        return "[2]223"
                } 0x0054 {
                        return "[2]64262"
                } 0x0073 {
                        return "[2]223"
                } 0x0074 {
                        return "[2]64262"
                }}
        } 0x0054 {
                switch ($___next_decimal) {
                0x0308 {
                        return "[2]7831"
                }}
        } 0x0057 {
                switch ($___next_decimal) {
                0x030A {
                        return "[2]7832"
                }}
        } 0x0059 {
                switch ($___next_decimal) {
                0x030A {
                        return "[2]7833"
                }}
        } 0x0069 {
                switch ($___next_decimal) {
                0x0307 {
                }}
        } 0x00DF {
        } 0x0130 {
                return "[1]105, 775"
        } 0x0149 {
        } 0x01F0 {
        } 0x02BC {
                switch ($___next_decimal) {
                0x004E {
                        return "[2]329"
                }}
        } 0x0386 {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]8116"
                } 0x0399 {
                        return "[2]8116"
                }}
        } 0x0389 {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]8132"
                } 0x0399 {
                        return "[2]8132"
                }}
        } 0x038F {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]8180"
                } 0x0399 {
                        return "[2]8180"
                }}
        } 0x0390 {
        } 0x0391 {
                switch ($___next_decimal) {
                0x0342 {
                        switch ($___third_decimal) {
                        0x0345 {
                                return "[3]8119"
                        } 0x0399 {
                                return "[3]8119"
                        } default {
                                return "[2]8118"
                        }}
                } 0x0399 {
                        return "[2]8115"
                }}
        } 0x0397 {
                switch ($___next_decimal) {
                0x0342 {
                        switch ($___third_decimal) {
                        0x0345 {
                                return "[3]8135"
                        } 0x0399 {
                                return "[3]8135"
                        } default {
                                return "[2]8134"
                        }}
                } 0x0399 {
                        return "[2]8131"
                }}
        } 0x0399 {
                switch ($___next_decimal) {
                0x0308 {
                        switch ($___third_decimal) {
                        0x0300 {
                                return "[3]8146"
                        } 0x0301 {
                                return "[3]912"
                        } 0x0342 {
                                return "[3]8151"
                        }}
                } 0x0342 {
                        return "[2]8150"
                }}
        } 0x03A1 {
                switch ($___next_decimal) {
                0x0313 {
                        return "[2]8164"
                }}
        } 0x03A3 {
                return "[1]962"
        } 0x03A5 {
                switch ($___next_decimal) {
                0x0308 {
                        switch ($___third_decimal) {
                        0x0300 {
                                return "[3]8162"
                        } 0x0301 {
                                return "[3]944"
                        } 0x0342 {
                                return "[3]8167"
                        }}
                } 0x0313 {
                        switch ($___third_decimal) {
                        0x0300 {
                                return "[3]8018"
                        } 0x0301 {
                                return "[3]8020"
                        } 0x0342 {
                                return "[3]8022"
                        } default {
                                return "[2]8016"
                        }}
                } 0x0342 {
                        return "[2]8166"
                }}
        } 0x03A9 {
                switch ($___next_decimal) {
                0x0342 {
                        switch ($___third_decimal) {
                        0x0345 {
                                return "[3]8183"
                        } 0x0399 {
                                return "[3]8183"
                        } default {
                                return "[2]8182"
                        }}
                } 0x0399 {
                        return "[2]8179"
                }}
        } 0x03B0 {
        } 0x03C2 {
        } 0x0535 {
                switch ($___next_decimal) {
                0x0552 {
                        return "[2]1415"
                } 0x0582 {
                        return "[2]1415"
                }}
        } 0x0544 {
                switch ($___next_decimal) {
                0x0535 {
                        return "[2]64276"
                } 0x053B {
                        return "[2]64277"
                } 0x053D {
                        return "[2]64279"
                } 0x0546 {
                        return "[2]64275"
                } 0x0565 {
                        return "[2]64276"
                } 0x056B {
                        return "[2]64277"
                } 0x056D {
                        return "[2]64279"
                } 0x0576 {
                        return "[2]64275"
                }}
        } 0x054E {
                switch ($___next_decimal) {
                0x0546 {
                        return "[2]64278"
                } 0x0576 {
                        return "[2]64278"
                }}
        } 0x0587 {
        } 0x1E96 {
        } 0x1E97 {
        } 0x1E98 {
        } 0x1E99 {
        } 0x1E9A {
        } 0x1F08 {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8064"
                }}
        } 0x1F09 {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8065"
                }}
        } 0x1F0A {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8066"
                }}
        } 0x1F0B {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8067"
                }}
        } 0x1F0C {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8068"
                }}
        } 0x1F0D {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8069"
                }}
        } 0x1F0E {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8070"
                }}
        } 0x1F0F {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8071"
                }}
        } 0x1F28 {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8080"
                }}
        } 0x1F29 {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8081"
                }}
        } 0x1F2A {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8082"
                }}
        } 0x1F2B {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8083"
                }}
        } 0x1F2C {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8084"
                }}
        } 0x1F2D {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8085"
                }}
        } 0x1F2E {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8086"
                }}
        } 0x1F2F {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8087"
                }}
        } 0x1F50 {
        } 0x1F52 {
        } 0x1F54 {
        } 0x1F56 {
        } 0x1F68 {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8096"
                }}
        } 0x1F69 {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8097"
                }}
        } 0x1F6A {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8098"
                }}
        } 0x1F6B {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8099"
                }}
        } 0x1F6C {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8100"
                }}
        } 0x1F6D {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8101"
                }}
        } 0x1F6E {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8102"
                }}
        } 0x1F6F {
                switch ($___next_decimal) {
                0x0399 {
                        return "[2]8103"
                }}
        } 0x1F80 {
        } 0x1F81 {
        } 0x1F82 {
        } 0x1F83 {
        } 0x1F84 {
        } 0x1F85 {
        } 0x1F86 {
        } 0x1F87 {
        } 0x1F88 {
                return "[1]8064"
        } 0x1F89 {
                return "[1]8065"
        } 0x1F8A {
                return "[1]8066"
        } 0x1F8B {
                return "[1]8067"
        } 0x1F8C {
                return "[1]8068"
        } 0x1F8D {
                return "[1]8069"
        } 0x1F8E {
                return "[1]8070"
        } 0x1F8F {
                return "[1]8071"
        } 0x1F90 {
        } 0x1F91 {
        } 0x1F92 {
        } 0x1F93 {
        } 0x1F94 {
        } 0x1F95 {
        } 0x1F96 {
        } 0x1F97 {
        } 0x1F98 {
                return "[1]8080"
        } 0x1F99 {
                return "[1]8081"
        } 0x1F9A {
                return "[1]8082"
        } 0x1F9B {
                return "[1]8083"
        } 0x1F9C {
                return "[1]8084"
        } 0x1F9D {
                return "[1]8085"
        } 0x1F9E {
                return "[1]8086"
        } 0x1F9F {
                return "[1]8087"
        } 0x1FA0 {
        } 0x1FA1 {
        } 0x1FA2 {
        } 0x1FA3 {
        } 0x1FA4 {
        } 0x1FA5 {
        } 0x1FA6 {
        } 0x1FA7 {
        } 0x1FA8 {
                return "[1]8096"
        } 0x1FA9 {
                return "[1]8097"
        } 0x1FAA {
                return "[1]8098"
        } 0x1FAB {
                return "[1]8099"
        } 0x1FAC {
                return "[1]8100"
        } 0x1FAD {
                return "[1]8101"
        } 0x1FAE {
                return "[1]8102"
        } 0x1FAF {
                return "[1]8103"
        } 0x1FB2 {
        } 0x1FB3 {
        } 0x1FB4 {
        } 0x1FB6 {
        } 0x1FB7 {
        } 0x1FBA {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]8114"
                } 0x0399 {
                        return "[2]8114"
                }}
        } 0x1FBC {
                return "[1]8115"
        } 0x1FC2 {
        } 0x1FC3 {
        } 0x1FC4 {
        } 0x1FC6 {
        } 0x1FC7 {
        } 0x1FCA {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]8130"
                } 0x0399 {
                        return "[2]8130"
                }}
        } 0x1FCC {
                return "[1]8131"
        } 0x1FD2 {
        } 0x1FD6 {
        } 0x1FD7 {
        } 0x1FE2 {
        } 0x1FE4 {
        } 0x1FE6 {
        } 0x1FE7 {
        } 0x1FF2 {
        } 0x1FF3 {
        } 0x1FF4 {
        } 0x1FF6 {
        } 0x1FF7 {
        } 0x1FFA {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]8178"
                } 0x0399 {
                        return "[2]8178"
                }}
        } 0x1FFC {
                return "[1]8179"
        } 0xFB00 {
        } 0xFB01 {
        } 0xFB02 {
        } 0xFB03 {
        } 0xFB04 {
        } 0xFB06 {
        } 0xFB13 {
        } 0xFB14 {
        } 0xFB15 {
        } 0xFB16 {
        } 0xFB17 {
        }}


        # switching non-special 1:1 casing now
        if  (($___char_decimal -ge 65) -and ($___char_decimal -le 90)) {
                return "[1]$($___char_decimal + 32)"
        } elseif  (($___char_decimal -ge 192) -and ($___char_decimal -le 214)) {
                return "[1]$($___char_decimal + 32)"
        } elseif  (($___char_decimal -ge 216) -and ($___char_decimal -le 222)) {
                return "[1]$($___char_decimal + 32)"
        } elseif  ($___char_decimal -eq 256) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 258) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 260) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 262) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 264) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 266) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 268) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 270) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 272) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 274) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 276) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 278) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 280) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 282) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 284) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 286) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 288) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 290) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 292) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 294) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 296) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 298) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 300) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 302) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 304) {
                return "[1]$($___char_decimal - 199)"
        } elseif  ($___char_decimal -eq 306) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 308) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 310) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 313) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 315) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 317) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 319) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 321) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 323) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 325) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 327) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 330) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 332) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 334) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 336) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 338) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 340) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 342) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 344) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 346) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 348) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 350) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 352) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 354) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 356) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 358) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 360) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 362) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 364) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 366) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 368) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 370) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 372) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 374) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 376) {
                return "[1]$($___char_decimal - 121)"
        } elseif  ($___char_decimal -eq 377) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 379) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 381) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 385) {
                return "[1]$($___char_decimal + 210)"
        } elseif  ($___char_decimal -eq 386) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 388) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 390) {
                return "[1]$($___char_decimal + 206)"
        } elseif  ($___char_decimal -eq 391) {
                return "[1]$($___char_decimal + 1)"
        } elseif  (($___char_decimal -ge 393) -and ($___char_decimal -le 394)) {
                return "[1]$($___char_decimal + 205)"
        } elseif  ($___char_decimal -eq 395) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 398) {
                return "[1]$($___char_decimal + 79)"
        } elseif  ($___char_decimal -eq 399) {
                return "[1]$($___char_decimal + 202)"
        } elseif  ($___char_decimal -eq 400) {
                return "[1]$($___char_decimal + 203)"
        } elseif  ($___char_decimal -eq 401) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 403) {
                return "[1]$($___char_decimal + 205)"
        } elseif  ($___char_decimal -eq 404) {
                return "[1]$($___char_decimal + 207)"
        } elseif  ($___char_decimal -eq 406) {
                return "[1]$($___char_decimal + 211)"
        } elseif  ($___char_decimal -eq 407) {
                return "[1]$($___char_decimal + 209)"
        } elseif  ($___char_decimal -eq 408) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 412) {
                return "[1]$($___char_decimal + 211)"
        } elseif  ($___char_decimal -eq 413) {
                return "[1]$($___char_decimal + 213)"
        } elseif  ($___char_decimal -eq 415) {
                return "[1]$($___char_decimal + 214)"
        } elseif  ($___char_decimal -eq 416) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 418) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 420) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 423) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 425) {
                return "[1]$($___char_decimal + 218)"
        } elseif  ($___char_decimal -eq 428) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 430) {
                return "[1]$($___char_decimal + 218)"
        } elseif  ($___char_decimal -eq 431) {
                return "[1]$($___char_decimal + 1)"
        } elseif  (($___char_decimal -ge 433) -and ($___char_decimal -le 434)) {
                return "[1]$($___char_decimal + 217)"
        } elseif  ($___char_decimal -eq 435) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 437) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 439) {
                return "[1]$($___char_decimal + 219)"
        } elseif  ($___char_decimal -eq 440) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 444) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 452) {
                return "[1]$($___char_decimal + 2)"
        } elseif  ($___char_decimal -eq 453) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 455) {
                return "[1]$($___char_decimal + 2)"
        } elseif  ($___char_decimal -eq 456) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 458) {
                return "[1]$($___char_decimal + 2)"
        } elseif  ($___char_decimal -eq 459) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 461) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 463) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 465) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 467) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 469) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 471) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 473) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 475) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 478) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 480) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 482) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 484) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 486) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 488) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 490) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 492) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 494) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 497) {
                return "[1]$($___char_decimal + 2)"
        } elseif  ($___char_decimal -eq 498) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 500) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 502) {
                return "[1]$($___char_decimal - 97)"
        } elseif  ($___char_decimal -eq 503) {
                return "[1]$($___char_decimal - 56)"
        } elseif  ($___char_decimal -eq 504) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 506) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 508) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 510) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 512) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 514) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 516) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 518) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 520) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 522) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 524) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 526) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 528) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 530) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 532) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 534) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 536) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 538) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 540) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 542) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 544) {
                return "[1]$($___char_decimal - 130)"
        } elseif  ($___char_decimal -eq 546) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 548) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 550) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 552) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 554) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 556) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 558) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 560) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 562) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 570) {
                return "[1]$($___char_decimal + 10795)"
        } elseif  ($___char_decimal -eq 571) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 573) {
                return "[1]$($___char_decimal - 163)"
        } elseif  ($___char_decimal -eq 574) {
                return "[1]$($___char_decimal + 10792)"
        } elseif  ($___char_decimal -eq 577) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 579) {
                return "[1]$($___char_decimal - 195)"
        } elseif  ($___char_decimal -eq 580) {
                return "[1]$($___char_decimal + 69)"
        } elseif  ($___char_decimal -eq 581) {
                return "[1]$($___char_decimal + 71)"
        } elseif  ($___char_decimal -eq 582) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 584) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 586) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 588) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 590) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 880) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 882) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 886) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 895) {
                return "[1]$($___char_decimal + 116)"
        } elseif  ($___char_decimal -eq 902) {
                return "[1]$($___char_decimal + 38)"
        } elseif  (($___char_decimal -ge 904) -and ($___char_decimal -le 906)) {
                return "[1]$($___char_decimal + 37)"
        } elseif  ($___char_decimal -eq 908) {
                return "[1]$($___char_decimal + 64)"
        } elseif  (($___char_decimal -ge 910) -and ($___char_decimal -le 911)) {
                return "[1]$($___char_decimal + 63)"
        } elseif  (($___char_decimal -ge 913) -and ($___char_decimal -le 929)) {
                return "[1]$($___char_decimal + 32)"
        } elseif  (($___char_decimal -ge 931) -and ($___char_decimal -le 939)) {
                return "[1]$($___char_decimal + 32)"
        } elseif  ($___char_decimal -eq 975) {
                return "[1]$($___char_decimal + 8)"
        } elseif  ($___char_decimal -eq 994) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 996) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 998) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1000) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1002) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1004) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1006) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1012) {
                return "[1]$($___char_decimal - 60)"
        } elseif  ($___char_decimal -eq 1015) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1017) {
                return "[1]$($___char_decimal - 7)"
        } elseif  ($___char_decimal -eq 1018) {
                return "[1]$($___char_decimal + 1)"
        } elseif  (($___char_decimal -ge 1021) -and ($___char_decimal -le 1023)) {
                return "[1]$($___char_decimal - 130)"
        } elseif  (($___char_decimal -ge 1024) -and ($___char_decimal -le 1039)) {
                return "[1]$($___char_decimal + 80)"
        } elseif  (($___char_decimal -ge 1040) -and ($___char_decimal -le 1071)) {
                return "[1]$($___char_decimal + 32)"
        } elseif  ($___char_decimal -eq 1120) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1122) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1124) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1126) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1128) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1130) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1132) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1134) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1136) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1138) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1140) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1142) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1144) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1146) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1148) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1150) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1152) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1162) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1164) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1166) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1168) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1170) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1172) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1174) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1176) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1178) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1180) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1182) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1184) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1186) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1188) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1190) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1192) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1194) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1196) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1198) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1200) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1202) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1204) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1206) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1208) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1210) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1212) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1214) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1217) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1219) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1221) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1223) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1225) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1227) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1229) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1232) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1234) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1236) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1238) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1240) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1242) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1244) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1246) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1248) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1250) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1252) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1254) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1256) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1258) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1260) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1262) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1264) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1266) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1268) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1270) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1272) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1274) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1276) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1278) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1280) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1282) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1284) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1286) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1288) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1290) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1292) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1294) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1296) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1298) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1300) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1302) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1304) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1306) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1308) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1310) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1312) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1314) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1316) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1318) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1320) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1322) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1324) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 1326) {
                return "[1]$($___char_decimal + 1)"
        } elseif  (($___char_decimal -ge 1329) -and ($___char_decimal -le 1366)) {
                return "[1]$($___char_decimal + 48)"
        } elseif  (($___char_decimal -ge 4256) -and ($___char_decimal -le 4293)) {
                return "[1]$($___char_decimal + 7264)"
        } elseif  ($___char_decimal -eq 4295) {
                return "[1]$($___char_decimal + 7264)"
        } elseif  ($___char_decimal -eq 4301) {
                return "[1]$($___char_decimal + 7264)"
        } elseif  (($___char_decimal -ge 7312) -and ($___char_decimal -le 7354)) {
                return "[1]$($___char_decimal - 3008)"
        } elseif  (($___char_decimal -ge 7357) -and ($___char_decimal -le 7359)) {
                return "[1]$($___char_decimal - 3008)"
        } elseif  ($___char_decimal -eq 7680) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7682) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7684) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7686) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7688) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7690) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7692) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7694) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7696) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7698) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7700) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7702) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7704) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7706) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7708) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7710) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7712) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7714) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7716) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7718) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7720) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7722) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7724) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7726) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7728) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7730) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7732) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7734) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7736) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7738) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7740) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7742) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7744) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7746) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7748) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7750) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7752) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7754) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7756) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7758) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7760) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7762) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7764) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7766) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7768) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7770) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7772) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7774) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7776) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7778) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7780) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7782) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7784) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7786) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7788) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7790) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7792) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7794) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7796) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7798) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7800) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7802) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7804) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7806) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7808) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7810) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7812) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7814) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7816) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7818) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7820) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7822) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7824) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7826) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7828) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7838) {
                return "[1]$($___char_decimal - 7615)"
        } elseif  ($___char_decimal -eq 7840) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7842) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7844) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7846) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7848) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7850) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7852) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7854) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7856) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7858) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7860) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7862) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7864) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7866) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7868) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7870) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7872) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7874) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7876) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7878) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7880) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7882) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7884) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7886) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7888) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7890) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7892) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7894) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7896) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7898) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7900) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7902) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7904) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7906) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7908) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7910) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7912) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7914) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7916) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7918) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7920) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7922) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7924) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7926) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7928) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7930) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7932) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 7934) {
                return "[1]$($___char_decimal + 1)"
        } elseif  (($___char_decimal -ge 7944) -and ($___char_decimal -le 7951)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 7960) -and ($___char_decimal -le 7965)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 7976) -and ($___char_decimal -le 7983)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 7992) -and ($___char_decimal -le 7999)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 8008) -and ($___char_decimal -le 8013)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  ($___char_decimal -eq 8025) {
                return "[1]$($___char_decimal - 8)"
        } elseif  ($___char_decimal -eq 8027) {
                return "[1]$($___char_decimal - 8)"
        } elseif  ($___char_decimal -eq 8029) {
                return "[1]$($___char_decimal - 8)"
        } elseif  ($___char_decimal -eq 8031) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 8040) -and ($___char_decimal -le 8047)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 8072) -and ($___char_decimal -le 8079)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 8088) -and ($___char_decimal -le 8095)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 8104) -and ($___char_decimal -le 8111)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 8120) -and ($___char_decimal -le 8121)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 8122) -and ($___char_decimal -le 8123)) {
                return "[1]$($___char_decimal - 74)"
        } elseif  ($___char_decimal -eq 8124) {
                return "[1]$($___char_decimal - 9)"
        } elseif  (($___char_decimal -ge 8136) -and ($___char_decimal -le 8139)) {
                return "[1]$($___char_decimal - 86)"
        } elseif  ($___char_decimal -eq 8140) {
                return "[1]$($___char_decimal - 9)"
        } elseif  (($___char_decimal -ge 8152) -and ($___char_decimal -le 8153)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 8154) -and ($___char_decimal -le 8155)) {
                return "[1]$($___char_decimal - 100)"
        } elseif  (($___char_decimal -ge 8168) -and ($___char_decimal -le 8169)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  (($___char_decimal -ge 8170) -and ($___char_decimal -le 8171)) {
                return "[1]$($___char_decimal - 112)"
        } elseif  ($___char_decimal -eq 8172) {
                return "[1]$($___char_decimal - 7)"
        } elseif  (($___char_decimal -ge 8184) -and ($___char_decimal -le 8185)) {
                return "[1]$($___char_decimal - 128)"
        } elseif  (($___char_decimal -ge 8186) -and ($___char_decimal -le 8187)) {
                return "[1]$($___char_decimal - 126)"
        } elseif  ($___char_decimal -eq 8188) {
                return "[1]$($___char_decimal - 9)"
        } elseif  ($___char_decimal -eq 8498) {
                return "[1]$($___char_decimal + 28)"
        } elseif  (($___char_decimal -ge 9398) -and ($___char_decimal -le 9423)) {
                return "[1]$($___char_decimal + 26)"
        } elseif  (($___char_decimal -ge 11264) -and ($___char_decimal -le 11311)) {
                return "[1]$($___char_decimal + 48)"
        } elseif  ($___char_decimal -eq 11360) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11362) {
                return "[1]$($___char_decimal - 10743)"
        } elseif  ($___char_decimal -eq 11363) {
                return "[1]$($___char_decimal - 3814)"
        } elseif  ($___char_decimal -eq 11364) {
                return "[1]$($___char_decimal - 10727)"
        } elseif  ($___char_decimal -eq 11367) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11369) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11371) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11373) {
                return "[1]$($___char_decimal - 10780)"
        } elseif  ($___char_decimal -eq 11374) {
                return "[1]$($___char_decimal - 10749)"
        } elseif  ($___char_decimal -eq 11375) {
                return "[1]$($___char_decimal - 10783)"
        } elseif  ($___char_decimal -eq 11376) {
                return "[1]$($___char_decimal - 10782)"
        } elseif  ($___char_decimal -eq 11378) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11381) {
                return "[1]$($___char_decimal + 1)"
        } elseif  (($___char_decimal -ge 11390) -and ($___char_decimal -le 11391)) {
                return "[1]$($___char_decimal - 10815)"
        } elseif  ($___char_decimal -eq 11392) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11394) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11396) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11398) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11400) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11402) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11404) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11406) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11408) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11410) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11412) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11414) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11416) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11418) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11420) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11422) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11424) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11426) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11428) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11430) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11432) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11434) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11436) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11438) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11440) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11442) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11444) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11446) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11448) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11450) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11452) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11454) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11456) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11458) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11460) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11462) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11464) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11466) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11468) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11470) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11472) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11474) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11476) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11478) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11480) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11482) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11484) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11486) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11488) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11490) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11499) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11501) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 11506) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42560) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42562) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42564) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42566) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42568) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42570) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42572) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42574) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42576) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42578) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42580) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42582) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42584) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42586) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42588) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42590) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42592) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42594) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42596) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42598) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42600) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42602) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42604) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42624) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42626) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42628) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42630) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42632) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42634) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42636) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42638) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42640) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42642) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42644) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42646) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42648) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42650) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42786) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42788) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42790) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42792) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42794) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42796) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42798) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42802) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42804) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42806) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42808) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42810) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42812) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42814) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42816) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42818) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42820) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42822) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42824) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42826) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42828) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42830) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42832) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42834) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42836) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42838) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42840) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42842) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42844) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42846) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42848) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42850) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42852) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42854) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42856) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42858) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42860) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42862) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42873) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42875) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42877) {
                return "[1]$($___char_decimal - 35332)"
        } elseif  ($___char_decimal -eq 42878) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42880) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42882) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42884) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42886) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42891) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42893) {
                return "[1]$($___char_decimal - 42280)"
        } elseif  ($___char_decimal -eq 42896) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42898) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42902) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42904) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42906) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42908) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42910) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42912) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42914) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42916) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42918) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42920) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42922) {
                return "[1]$($___char_decimal - 42308)"
        } elseif  ($___char_decimal -eq 42923) {
                return "[1]$($___char_decimal - 42319)"
        } elseif  ($___char_decimal -eq 42924) {
                return "[1]$($___char_decimal - 42315)"
        } elseif  ($___char_decimal -eq 42925) {
                return "[1]$($___char_decimal - 42305)"
        } elseif  ($___char_decimal -eq 42926) {
                return "[1]$($___char_decimal - 42308)"
        } elseif  ($___char_decimal -eq 42928) {
                return "[1]$($___char_decimal - 42258)"
        } elseif  ($___char_decimal -eq 42929) {
                return "[1]$($___char_decimal - 42282)"
        } elseif  ($___char_decimal -eq 42930) {
                return "[1]$($___char_decimal - 42261)"
        } elseif  ($___char_decimal -eq 42931) {
                return "[1]$($___char_decimal + 928)"
        } elseif  ($___char_decimal -eq 42932) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42934) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42936) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42938) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42940) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42942) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42944) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42946) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42948) {
                return "[1]$($___char_decimal - 48)"
        } elseif  ($___char_decimal -eq 42949) {
                return "[1]$($___char_decimal - 42307)"
        } elseif  ($___char_decimal -eq 42950) {
                return "[1]$($___char_decimal - 35384)"
        } elseif  ($___char_decimal -eq 42951) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42953) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42960) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42966) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42968) {
                return "[1]$($___char_decimal + 1)"
        } elseif  ($___char_decimal -eq 42997) {
                return "[1]$($___char_decimal + 1)"
        } elseif  (($___char_decimal -ge 65313) -and ($___char_decimal -le 65338)) {
                return "[1]$($___char_decimal + 32)"
        } elseif  (($___char_decimal -ge 66560) -and ($___char_decimal -le 66599)) {
                return "[1]$($___char_decimal + 40)"
        } elseif  (($___char_decimal -ge 66736) -and ($___char_decimal -le 66771)) {
                return "[1]$($___char_decimal + 40)"
        } elseif  (($___char_decimal -ge 66928) -and ($___char_decimal -le 66938)) {
                return "[1]$($___char_decimal + 39)"
        } elseif  (($___char_decimal -ge 66940) -and ($___char_decimal -le 66954)) {
                return "[1]$($___char_decimal + 39)"
        } elseif  (($___char_decimal -ge 66956) -and ($___char_decimal -le 66962)) {
                return "[1]$($___char_decimal + 39)"
        } elseif  (($___char_decimal -ge 66964) -and ($___char_decimal -le 66965)) {
                return "[1]$($___char_decimal + 39)"
        } elseif  (($___char_decimal -ge 68736) -and ($___char_decimal -le 68786)) {
                return "[1]$($___char_decimal + 64)"
        } elseif  (($___char_decimal -ge 71840) -and ($___char_decimal -le 71871)) {
                return "[1]$($___char_decimal + 32)"
        } elseif  (($___char_decimal -ge 93760) -and ($___char_decimal -le 93791)) {
                return "[1]$($___char_decimal + 32)"
        } else {
                return "[1]${___char_decimal}"
        }
}
