# Copyright 2024 HestiaKERNEL Authors
#
#
# Licensed under (Holloway) Chew, Kean Ho’s Liberal License (the "License").
# You must comply with the license to use the content. Get the License at:
#
#                 https://doi.org/10.5281/zenodo.13770769
#
# You MUST ensure any interaction with the content STRICTLY COMPLIES with
# the permissions and limitations set forth in the license.

# WARNING - Autogenerated script from 'HestiaKERNEL/src/unicode/data-parser.sh'.
#           DO NOT EDIT MANUALLY!




function hestiakernel-rune-to-upper {
        param (
                [uint32]$___char_decimal,
                [uint32]$___next_decimal,
                [uint32]$___third_decimal,
                [string]$___locale
        )


        # validate input
        if ($___char_decimal -eq "") {
                # ERROR - bad input
                return ""
        }


        # language sensitive special cases
        switch -Wildcard ($___locale) {
        { $_ -in "az*", "tr*" } {
                # Turkish & Azerbaijani
                switch ($___char_decimal) {
                0x0069 {
                        return "[1]304"
                } 0x0131 {
                        return "[1]73"
                }}
        } "lt*" {
                # Lithuanian
                switch ($___char_decimal) {
                0x0069 {
                        switch ($___next_decimal) {
                        0x0307 {
                                switch ($___third_decimal) {
                                0x0300 {
                                        return "[3]204"
                                } 0x0301 {
                                        return "[3]205"
                                } 0x0303 {
                                        return "[3]296"
                                } default {
                                        return "[2]73"
                                }}
                        }}
                } 0x006A {
                        switch ($___next_decimal) {
                        0x0307 {
                                return "[2]74"
                        }}
                } 0x012F {
                        switch ($___next_decimal) {
                        0x0307 {
                                return "[2]302"
                        }}
                } 0x0307 {
                        return "[1]"
                }}
        }}


        # language insensitive special cases
        switch ($___char_decimal) {
        "powershell-language-adjusting-first-case" {
                # just to make the first case consistent with others (as in
                # programming languages) without breaking the parser just for
                # PowerShell specific requirement.
        } 0x0041 {
                switch ($___next_decimal) {
                0x02BE {
                }}
        } 0x0046 {
                switch ($___next_decimal) {
                0x0046 {
                        switch ($___third_decimal) {
                        0x0049 {
                        } 0x004C {
                        } default {
                        }}
                } 0x0049 {
                } 0x004C {
                } 0x0066 {
                        switch ($___third_decimal) {
                        0x0069 {
                                return "[3]70, 70, 73"
                        } 0x006C {
                                return "[3]70, 70, 76"
                        } default {
                                return "[2]70, 70"
                        }}
                } 0x0069 {
                        return "[2]70, 73"
                } 0x006C {
                        return "[2]70, 76"
                }}
        } 0x0048 {
                switch ($___next_decimal) {
                0x0331 {
                }}
        } 0x004A {
                switch ($___next_decimal) {
                0x030C {
                }}
        } 0x0053 {
                switch ($___next_decimal) {
                0x0053 {
                } 0x0054 {
                } 0x0073 {
                        return "[2]83, 83"
                } 0x0074 {
                        return "[2]83, 84"
                }}
        } 0x0054 {
                switch ($___next_decimal) {
                0x0308 {
                }}
        } 0x0057 {
                switch ($___next_decimal) {
                0x030A {
                }}
        } 0x0059 {
                switch ($___next_decimal) {
                0x030A {
                }}
        } 0x0069 {
                switch ($___next_decimal) {
                0x0307 {
                        return "[2]304"
                }}
        } 0x00DF {
                return "[1]83, 83"
        } 0x0130 {
        } 0x0149 {
                return "[1]700, 78"
        } 0x01F0 {
                return "[1]74, 780"
        } 0x02BC {
                switch ($___next_decimal) {
                0x004E {
                }}
        } 0x0386 {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]902, 921"
                } 0x0399 {
                }}
        } 0x0389 {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]905, 921"
                } 0x0399 {
                }}
        } 0x038F {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]911, 921"
                } 0x0399 {
                }}
        } 0x0390 {
                return "[1]921, 776, 769"
        } 0x0391 {
                switch ($___next_decimal) {
                0x0342 {
                        switch ($___third_decimal) {
                        0x0345 {
                                return "[3]913, 834, 921"
                        } 0x0399 {
                        } default {
                        }}
                } 0x0399 {
                }}
        } 0x0397 {
                switch ($___next_decimal) {
                0x0342 {
                        switch ($___third_decimal) {
                        0x0345 {
                                return "[3]919, 834, 921"
                        } 0x0399 {
                        } default {
                        }}
                } 0x0399 {
                }}
        } 0x0399 {
                switch ($___next_decimal) {
                0x0308 {
                        switch ($___third_decimal) {
                        0x0300 {
                        } 0x0301 {
                        } 0x0342 {
                        }}
                } 0x0342 {
                }}
        } 0x03A1 {
                switch ($___next_decimal) {
                0x0313 {
                }}
        } 0x03A3 {
        } 0x03A5 {
                switch ($___next_decimal) {
                0x0308 {
                        switch ($___third_decimal) {
                        0x0300 {
                        } 0x0301 {
                        } 0x0342 {
                        }}
                } 0x0313 {
                        switch ($___third_decimal) {
                        0x0300 {
                        } 0x0301 {
                        } 0x0342 {
                        } default {
                        }}
                } 0x0342 {
                }}
        } 0x03A9 {
                switch ($___next_decimal) {
                0x0342 {
                        switch ($___third_decimal) {
                        0x0345 {
                                return "[3]937, 834, 921"
                        } 0x0399 {
                        } default {
                        }}
                } 0x0399 {
                }}
        } 0x03B0 {
                return "[1]933, 776, 769"
        } 0x03C2 {
                return "[1]931"
        } 0x0535 {
                switch ($___next_decimal) {
                0x0552 {
                } 0x0582 {
                        return "[2]1333, 1362"
                }}
        } 0x0544 {
                switch ($___next_decimal) {
                0x0535 {
                } 0x053B {
                } 0x053D {
                } 0x0546 {
                } 0x0565 {
                        return "[2]1348, 1333"
                } 0x056B {
                        return "[2]1348, 1339"
                } 0x056D {
                        return "[2]1348, 1341"
                } 0x0576 {
                        return "[2]1348, 1350"
                }}
        } 0x054E {
                switch ($___next_decimal) {
                0x0546 {
                } 0x0576 {
                        return "[2]1358, 1350"
                }}
        } 0x0587 {
                return "[1]1333, 1362"
        } 0x1E96 {
                return "[1]72, 817"
        } 0x1E97 {
                return "[1]84, 776"
        } 0x1E98 {
                return "[1]87, 778"
        } 0x1E99 {
                return "[1]89, 778"
        } 0x1E9A {
                return "[1]65, 702"
        } 0x1F08 {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F09 {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F0A {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F0B {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F0C {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F0D {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F0E {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F0F {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F28 {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F29 {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F2A {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F2B {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F2C {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F2D {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F2E {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F2F {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F50 {
                return "[1]933, 787"
        } 0x1F52 {
                return "[1]933, 787, 768"
        } 0x1F54 {
                return "[1]933, 787, 769"
        } 0x1F56 {
                return "[1]933, 787, 834"
        } 0x1F68 {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F69 {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F6A {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F6B {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F6C {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F6D {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F6E {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F6F {
                switch ($___next_decimal) {
                0x0399 {
                }}
        } 0x1F80 {
                return "[1]7944, 921"
        } 0x1F81 {
                return "[1]7945, 921"
        } 0x1F82 {
                return "[1]7946, 921"
        } 0x1F83 {
                return "[1]7947, 921"
        } 0x1F84 {
                return "[1]7948, 921"
        } 0x1F85 {
                return "[1]7949, 921"
        } 0x1F86 {
                return "[1]7950, 921"
        } 0x1F87 {
                return "[1]7951, 921"
        } 0x1F88 {
                return "[1]7944, 921"
        } 0x1F89 {
                return "[1]7945, 921"
        } 0x1F8A {
                return "[1]7946, 921"
        } 0x1F8B {
                return "[1]7947, 921"
        } 0x1F8C {
                return "[1]7948, 921"
        } 0x1F8D {
                return "[1]7949, 921"
        } 0x1F8E {
                return "[1]7950, 921"
        } 0x1F8F {
                return "[1]7951, 921"
        } 0x1F90 {
                return "[1]7976, 921"
        } 0x1F91 {
                return "[1]7977, 921"
        } 0x1F92 {
                return "[1]7978, 921"
        } 0x1F93 {
                return "[1]7979, 921"
        } 0x1F94 {
                return "[1]7980, 921"
        } 0x1F95 {
                return "[1]7981, 921"
        } 0x1F96 {
                return "[1]7982, 921"
        } 0x1F97 {
                return "[1]7983, 921"
        } 0x1F98 {
                return "[1]7976, 921"
        } 0x1F99 {
                return "[1]7977, 921"
        } 0x1F9A {
                return "[1]7978, 921"
        } 0x1F9B {
                return "[1]7979, 921"
        } 0x1F9C {
                return "[1]7980, 921"
        } 0x1F9D {
                return "[1]7981, 921"
        } 0x1F9E {
                return "[1]7982, 921"
        } 0x1F9F {
                return "[1]7983, 921"
        } 0x1FA0 {
                return "[1]8040, 921"
        } 0x1FA1 {
                return "[1]8041, 921"
        } 0x1FA2 {
                return "[1]8042, 921"
        } 0x1FA3 {
                return "[1]8043, 921"
        } 0x1FA4 {
                return "[1]8044, 921"
        } 0x1FA5 {
                return "[1]8045, 921"
        } 0x1FA6 {
                return "[1]8046, 921"
        } 0x1FA7 {
                return "[1]8047, 921"
        } 0x1FA8 {
                return "[1]8040, 921"
        } 0x1FA9 {
                return "[1]8041, 921"
        } 0x1FAA {
                return "[1]8042, 921"
        } 0x1FAB {
                return "[1]8043, 921"
        } 0x1FAC {
                return "[1]8044, 921"
        } 0x1FAD {
                return "[1]8045, 921"
        } 0x1FAE {
                return "[1]8046, 921"
        } 0x1FAF {
                return "[1]8047, 921"
        } 0x1FB2 {
                return "[1]8122, 921"
        } 0x1FB3 {
                return "[1]913, 921"
        } 0x1FB4 {
                return "[1]902, 921"
        } 0x1FB6 {
                return "[1]913, 834"
        } 0x1FB7 {
                return "[1]913, 834, 921"
        } 0x1FBA {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]8122, 921"
                } 0x0399 {
                }}
        } 0x1FBC {
                return "[1]913, 921"
        } 0x1FC2 {
                return "[1]8138, 921"
        } 0x1FC3 {
                return "[1]919, 921"
        } 0x1FC4 {
                return "[1]905, 921"
        } 0x1FC6 {
                return "[1]919, 834"
        } 0x1FC7 {
                return "[1]919, 834, 921"
        } 0x1FCA {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]8138, 921"
                } 0x0399 {
                }}
        } 0x1FCC {
                return "[1]919, 921"
        } 0x1FD2 {
                return "[1]921, 776, 768"
        } 0x1FD6 {
                return "[1]921, 834"
        } 0x1FD7 {
                return "[1]921, 776, 834"
        } 0x1FE2 {
                return "[1]933, 776, 768"
        } 0x1FE4 {
                return "[1]929, 787"
        } 0x1FE6 {
                return "[1]933, 834"
        } 0x1FE7 {
                return "[1]933, 776, 834"
        } 0x1FF2 {
                return "[1]8186, 921"
        } 0x1FF3 {
                return "[1]937, 921"
        } 0x1FF4 {
                return "[1]911, 921"
        } 0x1FF6 {
                return "[1]937, 834"
        } 0x1FF7 {
                return "[1]937, 834, 921"
        } 0x1FFA {
                switch ($___next_decimal) {
                0x0345 {
                        return "[2]8186, 921"
                } 0x0399 {
                }}
        } 0x1FFC {
                return "[1]937, 921"
        } 0xFB00 {
                return "[1]70, 70"
        } 0xFB01 {
                return "[1]70, 73"
        } 0xFB02 {
                return "[1]70, 76"
        } 0xFB03 {
                return "[1]70, 70, 73"
        } 0xFB04 {
                return "[1]70, 70, 76"
        } 0xFB06 {
                return "[1]83, 84"
        } 0xFB13 {
                return "[1]1348, 1350"
        } 0xFB14 {
                return "[1]1348, 1333"
        } 0xFB15 {
                return "[1]1348, 1339"
        } 0xFB16 {
                return "[1]1358, 1350"
        } 0xFB17 {
                return "[1]1348, 1341"
        }}


        # switching non-special 1:1 casing now
        if  (($___char_decimal -ge 97) -and ($___char_decimal -le 122)) {
                return "[1]$($___char_decimal - 32)"
        } elseif  (($___char_decimal -ge 224) -and ($___char_decimal -le 246)) {
                return "[1]$($___char_decimal - 32)"
        } elseif  (($___char_decimal -ge 248) -and ($___char_decimal -le 254)) {
                return "[1]$($___char_decimal - 32)"
        } elseif  ($___char_decimal -eq 255) {
                return "[1]$($___char_decimal + 121)"
        } elseif  ($___char_decimal -eq 257) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 259) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 261) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 263) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 265) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 267) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 269) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 271) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 273) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 275) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 277) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 279) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 281) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 283) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 285) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 287) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 289) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 291) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 293) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 295) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 297) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 299) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 301) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 303) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 305) {
                return "[1]$($___char_decimal - 232)"
        } elseif  ($___char_decimal -eq 307) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 309) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 311) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 314) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 316) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 318) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 320) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 322) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 324) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 326) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 328) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 331) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 333) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 335) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 337) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 339) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 341) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 343) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 345) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 347) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 349) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 351) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 353) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 355) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 357) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 359) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 361) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 363) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 365) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 367) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 369) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 371) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 373) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 375) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 378) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 380) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 382) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 383) {
                return "[1]$($___char_decimal - 300)"
        } elseif  ($___char_decimal -eq 384) {
                return "[1]$($___char_decimal + 195)"
        } elseif  ($___char_decimal -eq 387) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 389) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 392) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 396) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 402) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 405) {
                return "[1]$($___char_decimal + 97)"
        } elseif  ($___char_decimal -eq 409) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 410) {
                return "[1]$($___char_decimal + 163)"
        } elseif  ($___char_decimal -eq 414) {
                return "[1]$($___char_decimal + 130)"
        } elseif  ($___char_decimal -eq 417) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 419) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 421) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 424) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 429) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 432) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 436) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 438) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 441) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 445) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 454) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 457) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 460) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 462) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 464) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 466) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 468) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 470) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 472) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 474) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 476) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 477) {
                return "[1]$($___char_decimal - 79)"
        } elseif  ($___char_decimal -eq 479) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 481) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 483) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 485) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 487) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 489) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 491) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 493) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 495) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 499) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 501) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 505) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 507) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 509) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 511) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 513) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 515) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 517) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 519) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 521) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 523) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 525) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 527) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 529) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 531) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 533) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 535) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 537) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 539) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 541) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 543) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 547) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 549) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 551) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 553) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 555) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 557) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 559) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 561) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 563) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 572) {
                return "[1]$($___char_decimal - 1)"
        } elseif  (($___char_decimal -ge 575) -and ($___char_decimal -le 576)) {
                return "[1]$($___char_decimal + 10815)"
        } elseif  ($___char_decimal -eq 578) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 583) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 585) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 587) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 589) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 591) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 592) {
                return "[1]$($___char_decimal + 10783)"
        } elseif  ($___char_decimal -eq 593) {
                return "[1]$($___char_decimal + 10780)"
        } elseif  ($___char_decimal -eq 594) {
                return "[1]$($___char_decimal + 10782)"
        } elseif  ($___char_decimal -eq 595) {
                return "[1]$($___char_decimal - 210)"
        } elseif  ($___char_decimal -eq 596) {
                return "[1]$($___char_decimal - 206)"
        } elseif  (($___char_decimal -ge 598) -and ($___char_decimal -le 599)) {
                return "[1]$($___char_decimal - 205)"
        } elseif  ($___char_decimal -eq 601) {
                return "[1]$($___char_decimal - 202)"
        } elseif  ($___char_decimal -eq 603) {
                return "[1]$($___char_decimal - 203)"
        } elseif  ($___char_decimal -eq 604) {
                return "[1]$($___char_decimal + 42319)"
        } elseif  ($___char_decimal -eq 608) {
                return "[1]$($___char_decimal - 205)"
        } elseif  ($___char_decimal -eq 609) {
                return "[1]$($___char_decimal + 42315)"
        } elseif  ($___char_decimal -eq 611) {
                return "[1]$($___char_decimal - 207)"
        } elseif  ($___char_decimal -eq 613) {
                return "[1]$($___char_decimal + 42280)"
        } elseif  ($___char_decimal -eq 614) {
                return "[1]$($___char_decimal + 42308)"
        } elseif  ($___char_decimal -eq 616) {
                return "[1]$($___char_decimal - 209)"
        } elseif  ($___char_decimal -eq 617) {
                return "[1]$($___char_decimal - 211)"
        } elseif  ($___char_decimal -eq 619) {
                return "[1]$($___char_decimal + 10743)"
        } elseif  ($___char_decimal -eq 620) {
                return "[1]$($___char_decimal + 42305)"
        } elseif  ($___char_decimal -eq 623) {
                return "[1]$($___char_decimal - 211)"
        } elseif  ($___char_decimal -eq 625) {
                return "[1]$($___char_decimal + 10749)"
        } elseif  ($___char_decimal -eq 626) {
                return "[1]$($___char_decimal - 213)"
        } elseif  ($___char_decimal -eq 629) {
                return "[1]$($___char_decimal - 214)"
        } elseif  ($___char_decimal -eq 637) {
                return "[1]$($___char_decimal + 10727)"
        } elseif  ($___char_decimal -eq 642) {
                return "[1]$($___char_decimal + 42307)"
        } elseif  ($___char_decimal -eq 643) {
                return "[1]$($___char_decimal - 218)"
        } elseif  ($___char_decimal -eq 647) {
                return "[1]$($___char_decimal + 42282)"
        } elseif  ($___char_decimal -eq 648) {
                return "[1]$($___char_decimal - 218)"
        } elseif  ($___char_decimal -eq 649) {
                return "[1]$($___char_decimal - 69)"
        } elseif  (($___char_decimal -ge 650) -and ($___char_decimal -le 651)) {
                return "[1]$($___char_decimal - 217)"
        } elseif  ($___char_decimal -eq 652) {
                return "[1]$($___char_decimal - 71)"
        } elseif  ($___char_decimal -eq 658) {
                return "[1]$($___char_decimal - 219)"
        } elseif  ($___char_decimal -eq 669) {
                return "[1]$($___char_decimal + 42261)"
        } elseif  ($___char_decimal -eq 670) {
                return "[1]$($___char_decimal + 42258)"
        } elseif  ($___char_decimal -eq 881) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 883) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 887) {
                return "[1]$($___char_decimal - 1)"
        } elseif  (($___char_decimal -ge 891) -and ($___char_decimal -le 893)) {
                return "[1]$($___char_decimal + 130)"
        } elseif  ($___char_decimal -eq 940) {
                return "[1]$($___char_decimal - 38)"
        } elseif  (($___char_decimal -ge 941) -and ($___char_decimal -le 943)) {
                return "[1]$($___char_decimal - 37)"
        } elseif  (($___char_decimal -ge 945) -and ($___char_decimal -le 961)) {
                return "[1]$($___char_decimal - 32)"
        } elseif  ($___char_decimal -eq 962) {
                return "[1]$($___char_decimal - 31)"
        } elseif  (($___char_decimal -ge 963) -and ($___char_decimal -le 971)) {
                return "[1]$($___char_decimal - 32)"
        } elseif  ($___char_decimal -eq 972) {
                return "[1]$($___char_decimal - 64)"
        } elseif  (($___char_decimal -ge 973) -and ($___char_decimal -le 974)) {
                return "[1]$($___char_decimal - 63)"
        } elseif  ($___char_decimal -eq 985) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 987) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 989) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 991) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 993) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 995) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 997) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 999) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1001) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1003) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1005) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1007) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1016) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1019) {
                return "[1]$($___char_decimal - 1)"
        } elseif  (($___char_decimal -ge 1072) -and ($___char_decimal -le 1103)) {
                return "[1]$($___char_decimal - 32)"
        } elseif  (($___char_decimal -ge 1104) -and ($___char_decimal -le 1119)) {
                return "[1]$($___char_decimal - 80)"
        } elseif  ($___char_decimal -eq 1121) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1123) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1125) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1127) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1129) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1131) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1133) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1135) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1137) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1139) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1141) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1143) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1145) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1147) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1149) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1151) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1153) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1163) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1165) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1167) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1169) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1171) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1173) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1175) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1177) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1179) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1181) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1183) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1185) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1187) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1189) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1191) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1193) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1195) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1197) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1199) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1201) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1203) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1205) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1207) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1209) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1211) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1213) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1215) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1218) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1220) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1222) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1224) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1226) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1228) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1230) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1231) {
                return "[1]$($___char_decimal - 15)"
        } elseif  ($___char_decimal -eq 1233) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1235) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1237) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1239) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1241) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1243) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1245) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1247) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1249) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1251) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1253) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1255) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1257) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1259) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1261) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1263) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1265) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1267) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1269) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1271) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1273) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1275) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1277) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1279) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1281) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1283) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1285) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1287) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1289) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1291) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1293) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1295) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1297) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1299) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1301) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1303) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1305) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1307) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1309) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1311) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1313) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1315) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1317) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1319) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1321) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1323) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1325) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 1327) {
                return "[1]$($___char_decimal - 1)"
        } elseif  (($___char_decimal -ge 1377) -and ($___char_decimal -le 1414)) {
                return "[1]$($___char_decimal - 48)"
        } elseif  (($___char_decimal -ge 5112) -and ($___char_decimal -le 5117)) {
                return "[1]$($___char_decimal - 8)"
        } elseif  ($___char_decimal -eq 7296) {
                return "[1]$($___char_decimal - 6254)"
        } elseif  ($___char_decimal -eq 7297) {
                return "[1]$($___char_decimal - 6253)"
        } elseif  ($___char_decimal -eq 7298) {
                return "[1]$($___char_decimal - 6244)"
        } elseif  (($___char_decimal -ge 7299) -and ($___char_decimal -le 7300)) {
                return "[1]$($___char_decimal - 6242)"
        } elseif  ($___char_decimal -eq 7301) {
                return "[1]$($___char_decimal - 6243)"
        } elseif  ($___char_decimal -eq 7302) {
                return "[1]$($___char_decimal - 6236)"
        } elseif  ($___char_decimal -eq 7303) {
                return "[1]$($___char_decimal - 6181)"
        } elseif  ($___char_decimal -eq 7304) {
                return "[1]$($___char_decimal + 35266)"
        } elseif  ($___char_decimal -eq 7545) {
                return "[1]$($___char_decimal + 35332)"
        } elseif  ($___char_decimal -eq 7549) {
                return "[1]$($___char_decimal + 3814)"
        } elseif  ($___char_decimal -eq 7566) {
                return "[1]$($___char_decimal + 35384)"
        } elseif  ($___char_decimal -eq 7681) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7683) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7685) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7687) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7689) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7691) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7693) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7695) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7697) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7699) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7701) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7703) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7705) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7707) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7709) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7711) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7713) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7715) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7717) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7719) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7721) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7723) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7725) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7727) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7729) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7731) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7733) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7735) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7737) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7739) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7741) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7743) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7745) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7747) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7749) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7751) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7753) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7755) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7757) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7759) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7761) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7763) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7765) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7767) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7769) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7771) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7773) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7775) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7777) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7779) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7781) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7783) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7785) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7787) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7789) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7791) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7793) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7795) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7797) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7799) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7801) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7803) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7805) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7807) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7809) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7811) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7813) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7815) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7817) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7819) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7821) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7823) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7825) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7827) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7829) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7835) {
                return "[1]$($___char_decimal - 59)"
        } elseif  ($___char_decimal -eq 7841) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7843) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7845) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7847) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7849) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7851) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7853) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7855) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7857) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7859) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7861) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7863) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7865) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7867) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7869) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7871) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7873) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7875) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7877) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7879) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7881) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7883) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7885) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7887) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7889) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7891) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7893) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7895) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7897) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7899) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7901) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7903) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7905) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7907) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7909) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7911) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7913) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7915) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7917) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7919) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7921) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7923) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7925) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7927) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7929) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7931) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7933) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 7935) {
                return "[1]$($___char_decimal - 1)"
        } elseif  (($___char_decimal -ge 7936) -and ($___char_decimal -le 7943)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  (($___char_decimal -ge 7952) -and ($___char_decimal -le 7957)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  (($___char_decimal -ge 7968) -and ($___char_decimal -le 7975)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  (($___char_decimal -ge 7984) -and ($___char_decimal -le 7991)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  (($___char_decimal -ge 8000) -and ($___char_decimal -le 8005)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  ($___char_decimal -eq 8017) {
                return "[1]$($___char_decimal + 8)"
        } elseif  ($___char_decimal -eq 8019) {
                return "[1]$($___char_decimal + 8)"
        } elseif  ($___char_decimal -eq 8021) {
                return "[1]$($___char_decimal + 8)"
        } elseif  ($___char_decimal -eq 8023) {
                return "[1]$($___char_decimal + 8)"
        } elseif  (($___char_decimal -ge 8032) -and ($___char_decimal -le 8039)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  (($___char_decimal -ge 8048) -and ($___char_decimal -le 8049)) {
                return "[1]$($___char_decimal + 74)"
        } elseif  (($___char_decimal -ge 8050) -and ($___char_decimal -le 8053)) {
                return "[1]$($___char_decimal + 86)"
        } elseif  (($___char_decimal -ge 8054) -and ($___char_decimal -le 8055)) {
                return "[1]$($___char_decimal + 100)"
        } elseif  (($___char_decimal -ge 8056) -and ($___char_decimal -le 8057)) {
                return "[1]$($___char_decimal + 128)"
        } elseif  (($___char_decimal -ge 8058) -and ($___char_decimal -le 8059)) {
                return "[1]$($___char_decimal + 112)"
        } elseif  (($___char_decimal -ge 8060) -and ($___char_decimal -le 8061)) {
                return "[1]$($___char_decimal + 126)"
        } elseif  (($___char_decimal -ge 8064) -and ($___char_decimal -le 8071)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  (($___char_decimal -ge 8080) -and ($___char_decimal -le 8087)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  (($___char_decimal -ge 8096) -and ($___char_decimal -le 8103)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  (($___char_decimal -ge 8112) -and ($___char_decimal -le 8113)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  ($___char_decimal -eq 8115) {
                return "[1]$($___char_decimal + 9)"
        } elseif  ($___char_decimal -eq 8131) {
                return "[1]$($___char_decimal + 9)"
        } elseif  (($___char_decimal -ge 8144) -and ($___char_decimal -le 8145)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  (($___char_decimal -ge 8160) -and ($___char_decimal -le 8161)) {
                return "[1]$($___char_decimal + 8)"
        } elseif  ($___char_decimal -eq 8165) {
                return "[1]$($___char_decimal + 7)"
        } elseif  ($___char_decimal -eq 8179) {
                return "[1]$($___char_decimal + 9)"
        } elseif  ($___char_decimal -eq 8526) {
                return "[1]$($___char_decimal - 28)"
        } elseif  (($___char_decimal -ge 8560) -and ($___char_decimal -le 8575)) {
                return "[1]$($___char_decimal - 16)"
        } elseif  ($___char_decimal -eq 8580) {
                return "[1]$($___char_decimal - 1)"
        } elseif  (($___char_decimal -ge 9424) -and ($___char_decimal -le 9449)) {
                return "[1]$($___char_decimal - 26)"
        } elseif  (($___char_decimal -ge 11312) -and ($___char_decimal -le 11359)) {
                return "[1]$($___char_decimal - 48)"
        } elseif  ($___char_decimal -eq 11361) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11365) {
                return "[1]$($___char_decimal - 10795)"
        } elseif  ($___char_decimal -eq 11366) {
                return "[1]$($___char_decimal - 10792)"
        } elseif  ($___char_decimal -eq 11368) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11370) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11372) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11379) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11382) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11393) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11395) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11397) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11399) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11401) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11403) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11405) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11407) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11409) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11411) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11413) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11415) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11417) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11419) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11421) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11423) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11425) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11427) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11429) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11431) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11433) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11435) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11437) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11439) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11441) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11443) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11445) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11447) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11449) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11451) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11453) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11455) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11457) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11459) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11461) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11463) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11465) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11467) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11469) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11471) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11473) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11475) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11477) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11479) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11481) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11483) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11485) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11487) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11489) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11491) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11500) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11502) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 11507) {
                return "[1]$($___char_decimal - 1)"
        } elseif  (($___char_decimal -ge 11520) -and ($___char_decimal -le 11557)) {
                return "[1]$($___char_decimal - 7264)"
        } elseif  ($___char_decimal -eq 11559) {
                return "[1]$($___char_decimal - 7264)"
        } elseif  ($___char_decimal -eq 11565) {
                return "[1]$($___char_decimal - 7264)"
        } elseif  ($___char_decimal -eq 42561) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42563) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42565) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42567) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42569) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42571) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42573) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42575) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42577) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42579) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42581) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42583) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42585) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42587) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42589) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42591) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42593) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42595) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42597) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42599) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42601) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42603) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42605) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42625) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42627) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42629) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42631) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42633) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42635) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42637) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42639) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42641) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42643) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42645) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42647) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42649) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42651) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42787) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42789) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42791) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42793) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42795) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42797) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42799) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42803) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42805) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42807) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42809) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42811) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42813) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42815) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42817) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42819) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42821) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42823) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42825) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42827) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42829) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42831) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42833) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42835) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42837) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42839) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42841) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42843) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42845) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42847) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42849) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42851) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42853) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42855) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42857) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42859) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42861) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42863) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42874) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42876) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42879) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42881) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42883) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42885) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42887) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42892) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42897) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42899) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42900) {
                return "[1]$($___char_decimal + 48)"
        } elseif  ($___char_decimal -eq 42903) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42905) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42907) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42909) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42911) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42913) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42915) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42917) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42919) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42921) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42933) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42935) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42937) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42939) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42941) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42943) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42945) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42947) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42952) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42954) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42961) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42967) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42969) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 42998) {
                return "[1]$($___char_decimal - 1)"
        } elseif  ($___char_decimal -eq 43859) {
                return "[1]$($___char_decimal - 928)"
        } elseif  (($___char_decimal -ge 43888) -and ($___char_decimal -le 43967)) {
                return "[1]$($___char_decimal - 38864)"
        } elseif  (($___char_decimal -ge 65345) -and ($___char_decimal -le 65370)) {
                return "[1]$($___char_decimal - 32)"
        } elseif  (($___char_decimal -ge 66600) -and ($___char_decimal -le 66639)) {
                return "[1]$($___char_decimal - 40)"
        } elseif  (($___char_decimal -ge 66776) -and ($___char_decimal -le 66811)) {
                return "[1]$($___char_decimal - 40)"
        } elseif  (($___char_decimal -ge 66967) -and ($___char_decimal -le 66977)) {
                return "[1]$($___char_decimal - 39)"
        } elseif  (($___char_decimal -ge 66979) -and ($___char_decimal -le 66993)) {
                return "[1]$($___char_decimal - 39)"
        } elseif  (($___char_decimal -ge 66995) -and ($___char_decimal -le 67001)) {
                return "[1]$($___char_decimal - 39)"
        } elseif  (($___char_decimal -ge 67003) -and ($___char_decimal -le 67004)) {
                return "[1]$($___char_decimal - 39)"
        } elseif  (($___char_decimal -ge 68800) -and ($___char_decimal -le 68850)) {
                return "[1]$($___char_decimal - 64)"
        } elseif  (($___char_decimal -ge 71872) -and ($___char_decimal -le 71903)) {
                return "[1]$($___char_decimal - 32)"
        } elseif  (($___char_decimal -ge 93792) -and ($___char_decimal -le 93823)) {
                return "[1]$($___char_decimal - 32)"
        } else {
                return "[1]${___char_decimal}"
        }
}
