# Copyright 2024 (Holloway) Chew, Kean Ho <hello@hollowaykeanho.com>
#
#
# Licensed under (Holloway) Chew, Kean Ho’s Liberal License (the "License").
# You must comply with the license to use the content. Get the License at:
#
#                 https://doi.org/10.5281/zenodo.13770769
#
# You MUST ensure any interaction with the content STRICTLY COMPLIES with
# the permissions and limitations set forth in the license.
${env:HestiaKERNEL_ERROR_OK} = 0
${env:HestiaKERNEL_ERROR_BAD_EXEC} = 1
${env:HestiaKERNEL_ERROR_BAD_BUSY} = 2
${env:HestiaKERNEL_ERROR_BAD_DESCRIPTOR} = 3
${env:HestiaKERNEL_ERROR_BAD_EXCHANGE} = 4
${env:HestiaKERNEL_ERROR_BAD_MOUNT} = 5
${env:HestiaKERNEL_ERROR_BAD_PIPE} = 6
${env:HestiaKERNEL_ERROR_BAD_REQUEST} = 7
${env:HestiaKERNEL_ERROR_BAD_STREAM_PIPE} = 8
${env:HestiaKERNEL_ERROR_PROCESS_IS_DEAD} = 9
${env:HestiaKERNEL_ERROR_CANCELLED} = 10
${env:HestiaKERNEL_ERROR_CLEANING_REQUIRED} = 11
${env:HestiaKERNEL_ERROR_DEADLOCK} = 12
${env:HestiaKERNEL_ERROR_EXPIRED} = 13
${env:HestiaKERNEL_ERROR_ILLEGAL_BYTE_SEQUENCE} = 14
${env:HestiaKERNEL_ERROR_ILLEGAL_SEEK} = 15
${env:HestiaKERNEL_ERROR_INVALID_ARGUMENT} = 16
${env:HestiaKERNEL_ERROR_IS_EMPTY} = 17
${env:HestiaKERNEL_ERROR_MAXED_EXCHANGE} = 18
${env:HestiaKERNEL_ERROR_MAXED_QUOTA} = 19
${env:HestiaKERNEL_ERROR_MISSING_LOCK} = 20
${env:HestiaKERNEL_ERROR_IS_NOT_EMPTY} = 21
${env:HestiaKERNEL_ERROR_NOT_PERMITTED} = 22
${env:HestiaKERNEL_ERROR_NOT_POSSIBLE} = 23
${env:HestiaKERNEL_ERROR_NOT_POSSIBLE_BY_RFKILL} = 24
${env:HestiaKERNEL_ERROR_NOT_RECOVERABLE} = 25
${env:HestiaKERNEL_ERROR_OUT_OF_RANGE} = 26
${env:HestiaKERNEL_ERROR_PERMISSION_DENIED} = 27
${env:HestiaKERNEL_ERROR_TIMEOUT} = 28
${env:HestiaKERNEL_ERROR_TOO_MANY_READ} = 29
${env:HestiaKERNEL_ERROR_TOO_MANY_LOOP} = 30
${env:HestiaKERNEL_ERROR_TOO_MANY_REFERENCES} = 31
${env:HestiaKERNEL_ERROR_TOO_MANY_LINK} = 32
${env:HestiaKERNEL_ERROR_TOO_MANY_OPENED} = 33
${env:HestiaKERNEL_ERROR_TRY_AGAIN} = 34
${env:HestiaKERNEL_ERROR_UNSUPPORTED} = 35
${env:HestiaKERNEL_ERROR_WOULD_BLOCK} = 36




# lifecycle states
${env:HestiaKERNEL_ERROR_RESTART} = 37
${env:HestiaKERNEL_ERROR_RESUME} = 38
${env:HestiaKERNEL_ERROR_SHUTDOWN} = 39
${env:HestiaKERNEL_ERROR_SLEEP} = 40
${env:HestiaKERNEL_ERROR_STALLED} = 41
${env:HestiaKERNEL_ERROR_STANDBY} = 42
${env:HestiaKERNEL_ERROR_UNRESPONSIVE} = 43
${env:HestiaKERNEL_ERROR_TERMINATE} = 44
${env:HestiaKERNEL_ERROR_PROGRESS_SCHEDULED} = 45
${env:HestiaKERNEL_ERROR_PROGRESS_ALREADY_EXECUTING} = 46
${env:HestiaKERNEL_ERROR_PROGRESS_EXECUTING} = 47
${env:HestiaKERNEL_ERROR_PROGRESS_COMPLETED} = 48
${env:HestiaKERNEL_ERROR_PROGRESS_UNRESPONSIVE} = 49
${env:HestiaKERNEL_ERROR_PROGRESS_TERMINATE} = 50




# tri-tier inter-package communications
${env:HestiaKERNEL_ERROR_LV1_NOT_SYNC} = 51
${env:HestiaKERNEL_ERROR_LV1_PAUSED} = 52
${env:HestiaKERNEL_ERROR_LV1_RESET} = 53
${env:HestiaKERNEL_ERROR_LV2_NOT_SYNC} = 54
${env:HestiaKERNEL_ERROR_LV2_PAUSED} = 55
${env:HestiaKERNEL_ERROR_LV2_RESET} = 56
${env:HestiaKERNEL_ERROR_LV3_NOT_SYNC} = 57
${env:HestiaKERNEL_ERROR_LV3_PAUSED} = 58
${env:HestiaKERNEL_ERROR_LV3_RESET} = 59




# data (input/output parameters type etc)
${env:HestiaKERNEL_ERROR_DATA_BAD} = 60
${env:HestiaKERNEL_ERROR_DATA_EMPTY} = 61
${env:HestiaKERNEL_ERROR_DATA_INVALID} = 62
${env:HestiaKERNEL_ERROR_DATA_IS_UNIQUE} = 63
${env:HestiaKERNEL_ERROR_DATA_IS_NOT_UNIQUE} = 64
${env:HestiaKERNEL_ERROR_DATA_BUSY} = 65
${env:HestiaKERNEL_ERROR_DATA_DEAD} = 66
${env:HestiaKERNEL_ERROR_DATA_EXISTS} = 67
${env:HestiaKERNEL_ERROR_DATA_FAULTY} = 68
${env:HestiaKERNEL_ERROR_DATA_MISSING} = 69
${env:HestiaKERNEL_ERROR_DATA_OVERFLOW} = 70
${env:HestiaKERNEL_ERROR_DATA_POISONED} = 71
${env:HestiaKERNEL_ERROR_DATA_REMOVED} = 72
${env:HestiaKERNEL_ERROR_DATA_TOO_BIG} = 73
${env:HestiaKERNEL_ERROR_DATA_TOO_MANY_OPENED} = 74
${env:HestiaKERNEL_ERROR_DATA_TOO_LONG} = 75
${env:HestiaKERNEL_ERROR_DATA_MISMATCHED} = 76
${env:HestiaKERNEL_ERROR_DATA_IS_NOT_DIRECTORY} = 77
${env:HestiaKERNEL_ERROR_DATA_IS_NOT_FILE} = 78
${env:HestiaKERNEL_ERROR_DATA_IS_NOT_LINK} = 79
${env:HestiaKERNEL_ERROR_DATA_IS_NOT_SOCKET} = 80
${env:HestiaKERNEL_ERROR_DATA_REMOTE_CHANGED} = 81
${env:HestiaKERNEL_ERROR_DATA_REMOTE_ERROR} = 82
${env:HestiaKERNEL_ERROR_DATA_REMOTE_IO} = 83
${env:HestiaKERNEL_ERROR_DATA_MISSING_STREAMABLE_RESOURCES} = 84
${env:HestiaKERNEL_ERROR_DATA_NOT_STREAMABLE} = 85




# entity (device file directory object etc)
${env:HestiaKERNEL_ERROR_ENTITY_BAD} = 86
${env:HestiaKERNEL_ERROR_ENTITY_EMPTY} = 87
${env:HestiaKERNEL_ERROR_ENTITY_INVALID} = 88
${env:HestiaKERNEL_ERROR_ENTITY_IS_UNIQUE} = 89
${env:HestiaKERNEL_ERROR_ENTITY_IS_NOT_UNIQUE} = 90
${env:HestiaKERNEL_ERROR_ENTITY_BUSY} = 91
${env:HestiaKERNEL_ERROR_ENTITY_DEAD} = 92
${env:HestiaKERNEL_ERROR_ENTITY_EXISTS} = 93
${env:HestiaKERNEL_ERROR_ENTITY_FAULTY} = 94
${env:HestiaKERNEL_ERROR_ENTITY_MISSING} = 95
${env:HestiaKERNEL_ERROR_ENTITY_MISSING_CHILD} = 96
${env:HestiaKERNEL_ERROR_ENTITY_OUT_OF_BUFFER} = 97
${env:HestiaKERNEL_ERROR_ENTITY_POISONED} = 98
${env:HestiaKERNEL_ERROR_ENTITY_REMOVED} = 99
${env:HestiaKERNEL_ERROR_ENTITY_TOO_BIG} = 100
${env:HestiaKERNEL_ERROR_ENTITY_TOO_MANY_OPENED} = 101
${env:HestiaKERNEL_ERROR_ENTITY_UNATTACHED} = 102
${env:HestiaKERNEL_ERROR_ENTITY_MISMATCHED} = 103
${env:HestiaKERNEL_ERROR_ENTITY_IS_NOT_DIRECTORY} = 104
${env:HestiaKERNEL_ERROR_ENTITY_IS_NOT_FILE} = 105
${env:HestiaKERNEL_ERROR_ENTITY_IS_NOT_LINK} = 106
${env:HestiaKERNEL_ERROR_ENTITY_IS_NOT_SOCKET} = 107
${env:HestiaKERNEL_ERROR_ENTITY_REMOTE_CHANGED} = 108
${env:HestiaKERNEL_ERROR_ENTITY_REMOTE_ERROR} = 109
${env:HestiaKERNEL_ERROR_ENTITY_REMOTE_IO} = 110
${env:HestiaKERNEL_ERROR_ENTITY_MISSING_STREAMABLE_RESOURCES} = 111
${env:HestiaKERNEL_ERROR_ENTITY_NOT_STREAMABLE} = 112
${env:HestiaKERNEL_ERROR_ENTITY_STREAMABLE} = 113
${env:HestiaKERNEL_ERROR_ENTITY_A_TYPEWRITER} = 114
${env:HestiaKERNEL_ERROR_ENTITY_NOT_A_TYPEWRITER} = 115
${env:HestiaKERNEL_ERROR_ENTITY_BAD_DESCRIPTOR} = 116
${env:HestiaKERNEL_ERROR_ENTITY_FILETABLE_OVERFLOW} = 117




# key (cryptography)
${env:HestiaKERNEL_ERROR_KEY_BAD} = 118
${env:HestiaKERNEL_ERROR_KEY_DESTROYED} = 119
${env:HestiaKERNEL_ERROR_KEY_EXPIRED} = 120
${env:HestiaKERNEL_ERROR_KEY_MISSING} = 121
${env:HestiaKERNEL_ERROR_KEY_REJECTED} = 122
${env:HestiaKERNEL_ERROR_KEY_REVOKED} = 123




# library
${env:HestiaKERNEL_ERROR_LIBRARY_BAD} = 124
${env:HestiaKERNEL_ERROR_LIBRARY_CORRUPTED} = 125
${env:HestiaKERNEL_ERROR_LIBRARY_EXEC_FAILED} = 126
${env:HestiaKERNEL_ERROR_LIBRARY_MAXED} = 127
${env:HestiaKERNEL_ERROR_LIBRARY_MISSING} = 128




# network
${env:HestiaKERNEL_ERROR_NETWORK_BAD} = 129
${env:HestiaKERNEL_ERROR_NETWORK_BAD_AD} = 130
${env:HestiaKERNEL_ERROR_NETWORK_DOWN} = 131
${env:HestiaKERNEL_ERROR_NETWORK_NOT_CONNECTED} = 132
${env:HestiaKERNEL_ERROR_NETWORK_RESET} = 133
${env:HestiaKERNEL_ERROR_NETWORK_RFS} = 134
${env:HestiaKERNEL_ERROR_NETWORK_UNREACHABLE} = 135

${env:HestiaKERNEL_ERROR_NETWORK_HOST_DOWN} = 136
${env:HestiaKERNEL_ERROR_NETWORK_HOST_UNREACHABLE} = 137
${env:HestiaKERNEL_ERROR_NETWORK_SOCKET_UNSUPPORTED} = 138

${env:HestiaKERNEL_ERROR_NETWORK_ADDRESS_IN_USE} = 139
${env:HestiaKERNEL_ERROR_NETWORK_ADDRESS_UNAVAILABLE} = 140

${env:HestiaKERNEL_ERROR_NETWORK_CONN_ABORTED} = 141
${env:HestiaKERNEL_ERROR_NETWORK_CONN_IS_CONNECTED} = 142
${env:HestiaKERNEL_ERROR_NETWORK_CONN_MISSING_DEST_ADDRESS} = 143
${env:HestiaKERNEL_ERROR_NETWORK_CONN_MULTIHOP} = 144
${env:HestiaKERNEL_ERROR_NETWORK_CONN_NOT_CONNECTED} = 145
${env:HestiaKERNEL_ERROR_NETWORK_CONN_REFUSED} = 146
${env:HestiaKERNEL_ERROR_NETWORK_CONN_RESET} = 147

${env:HestiaKERNEL_ERROR_NETWORK_PAYLOAD_BAD} = 148
${env:HestiaKERNEL_ERROR_NETWORK_PAYLOAD_EMPTY} = 149
${env:HestiaKERNEL_ERROR_NETWORK_PAYLOAD_MISSING} = 150
${env:HestiaKERNEL_ERROR_NETWORK_PAYLOAD_TOO_LONG} = 151




# protocol
${env:HestiaKERNEL_ERROR_PROTOCOL_ADDRESS_UNSUPPORTED} = 152
${env:HestiaKERNEL_ERROR_PROTOCOL_BAD} = 153
${env:HestiaKERNEL_ERROR_PROTOCOL_FAMILY_UNSUPPORTED} = 154
${env:HestiaKERNEL_ERROR_PROTOCOL_MISSING} = 155
${env:HestiaKERNEL_ERROR_PROTOCOL_INVALID} = 156
${env:HestiaKERNEL_ERROR_PROTOCOL_FAULTY} = 157
${env:HestiaKERNEL_ERROR_PROTOCOL_EMPTY} = 158
${env:HestiaKERNEL_ERROR_PROTOCOL_UNSUPPORTED} = 159




# system (e.g. os interactable system)
${env:HestiaKERNEL_ERROR_SYSTEM_BAD_IO} = 160
${env:HestiaKERNEL_ERROR_SYSTEM_DEVICE_CROSS_LINK} = 161
${env:HestiaKERNEL_ERROR_SYSTEM_INTERRUPT_CALL} = 162
${env:HestiaKERNEL_ERROR_SYSTEM_INVALID} = 163
${env:HestiaKERNEL_ERROR_SYSTEM_MISSING_BLOCK_DEVICE} = 164
${env:HestiaKERNEL_ERROR_SYSTEM_MISSING_DEVICE} = 165
${env:HestiaKERNEL_ERROR_SYSTEM_MISSING_IO} = 166
${env:HestiaKERNEL_ERROR_SYSTEM_MISSING_PROCESS} = 167
${env:HestiaKERNEL_ERROR_SYSTEM_OUT_OF_DOMAIN} = 168
${env:HestiaKERNEL_ERROR_SYSTEM_OUT_OF_MEMORY} = 169
${env:HestiaKERNEL_ERROR_SYSTEM_OUT_OF_SPACE} = 170
${env:HestiaKERNEL_ERROR_SYSTEM_READ_ONLY_FILESYSTEM} = 171




# user
${env:HestiaKERNEL_ERROR_USER_ACCESS_BANNED} = 172
${env:HestiaKERNEL_ERROR_USER_ACCESS_LOCKED} = 173
${env:HestiaKERNEL_ERROR_USER_ACCESS_NOT_VERIFIED} = 174
${env:HestiaKERNEL_ERROR_USER_ACCESS_BAD} = 175
${env:HestiaKERNEL_ERROR_USER_ACCESS_REJECTED} = 176
${env:HestiaKERNEL_ERROR_USER_ACCESS_REVOKED} = 177
${env:HestiaKERNEL_ERROR_USER_ACCESS_EXISTS} = 178
${env:HestiaKERNEL_ERROR_USER_ACCESS_EMPTY} = 179
${env:HestiaKERNEL_ERROR_USER_ACCESS_MISSING} = 180
${env:HestiaKERNEL_ERROR_USER_ACCESS_INVALID} = 181
${env:HestiaKERNEL_ERROR_USER_ACCESS_EXPIRED} = 182
${env:HestiaKERNEL_ERROR_USER_ACCESS_MISMATCHED} = 183

${env:HestiaKERNEL_ERROR_USER_MFA_BANNED} = 184
${env:HestiaKERNEL_ERROR_USER_MFA_LOCKED} = 185
${env:HestiaKERNEL_ERROR_USER_MFA_NOT_VERIFIED} = 186
${env:HestiaKERNEL_ERROR_USER_MFA_BAD} = 188
${env:HestiaKERNEL_ERROR_USER_MFA_REJECTED} = 189
${env:HestiaKERNEL_ERROR_USER_MFA_REVOKED} = 190
${env:HestiaKERNEL_ERROR_USER_MFA_EXISTS} = 191
${env:HestiaKERNEL_ERROR_USER_MFA_EMPTY} = 192
${env:HestiaKERNEL_ERROR_USER_MFA_MISSING} = 193
${env:HestiaKERNEL_ERROR_USER_MFA_INVALID} = 194
${env:HestiaKERNEL_ERROR_USER_MFA_EXPIRED} = 195
${env:HestiaKERNEL_ERROR_USER_MFA_MISMATCHED} = 196

${env:HestiaKERNEL_ERROR_USER_ID_EXISTS} = 197
${env:HestiaKERNEL_ERROR_USER_ID_BANNED} = 198
${env:HestiaKERNEL_ERROR_USER_ID_BAD} = 199
${env:HestiaKERNEL_ERROR_USER_ID_LOCKED} = 200
${env:HestiaKERNEL_ERROR_USER_ID_NOT_VERIFIED} = 201
${env:HestiaKERNEL_ERROR_USER_ID_EMPTY} = 202
${env:HestiaKERNEL_ERROR_USER_ID_MISSING} = 203
${env:HestiaKERNEL_ERROR_USER_ID_INVALID} = 204
${env:HestiaKERNEL_ERROR_USER_ID_EXPIRED} = 205
${env:HestiaKERNEL_ERROR_USER_ID_MISMATCHED} = 206
${env:HestiaKERNEL_ERROR_USER_ID_DELETED} = 207
${env:HestiaKERNEL_ERROR_USER_PASSWORD_EXISTS} = 208
${env:HestiaKERNEL_ERROR_USER_PASSWORD_BANNED} = 209
${env:HestiaKERNEL_ERROR_USER_PASSWORD_BAD} = 210
${env:HestiaKERNEL_ERROR_USER_PASSWORD_REJECTED} = 211
${env:HestiaKERNEL_ERROR_USER_PASSWORD_REVOKED} = 212
${env:HestiaKERNEL_ERROR_USER_PASSWORD_EMPTY} = 213
${env:HestiaKERNEL_ERROR_USER_PASSWORD_MISSING} = 214
${env:HestiaKERNEL_ERROR_USER_PASSWORD_INVALID} = 215
${env:HestiaKERNEL_ERROR_USER_PASSWORD_EXPIRED} = 216
${env:HestiaKERNEL_ERROR_USER_PASSWORD_MISMATCHED} = 217
${env:HestiaKERNEL_ERROR_USER_KEY_EXISTS} = 218
${env:HestiaKERNEL_ERROR_USER_KEY_BANNED} = 219
${env:HestiaKERNEL_ERROR_USER_KEY_BAD} = 220
${env:HestiaKERNEL_ERROR_USER_KEY_REJECTED} = 221
${env:HestiaKERNEL_ERROR_USER_KEY_REVOKED} = 222
${env:HestiaKERNEL_ERROR_USER_KEY_EMPTY} = 223
${env:HestiaKERNEL_ERROR_USER_KEY_MISSING} = 224
${env:HestiaKERNEL_ERROR_USER_KEY_INVALID} = 225
${env:HestiaKERNEL_ERROR_USER_KEY_EXPIRED} = 226
${env:HestiaKERNEL_ERROR_USER_KEY_MISMATCHED} = 227
